services:

  db:
    image: postgres:latest
    volumes:
      - test-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "password"
    mem_limit: 512M
    ports:
      - "127.0.0.1:5432:5432"

volumes:
  test-postgres:

